# description of this workflow, can be anything you want
name: CurseForge - Package and Release - All pushes

# Deploy on all pushes to master, except '.github/**' folder.
on:
  push:
    branches:
      - master
    tags:
      - '*'
    paths-ignore:
      - '.github/**'

jobs:

  cf-release:
  
    runs-on: ubuntu-latest
    
    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      WAGO_API_TOKEN : ${{ secrets.WAGO_API_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}  # "GITHUB_TOKEN" is a secret always provided to the workflow
                                                 # for your own token, the name cannot start with "GITHUB_"

    steps:
    
      - uses: leafo/gh-actions-lua@v8.0.0
      - uses: actions/checkout@v1
        with:
          fetch-depth: 100 # for automated history

      - name: Create Changelog
        run: lua Plater_ChangeLog.lua latest >> CHANGELOG.md

      - name: Package and Release - Retail
        uses: BigWigsMods/packager@master
        with:
          args: -g retail -n "{project-version}-Retail"

      - name: Package and release for BC
        uses: BigWigsMods/packager@master
        with:
          args: -g bc -n "{project-version}{classic}"
          
